Controllers/HomeController.cs
using Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExemploMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {   
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/PaginasController.cs
using Business;
using System;
using System.Web.Mvc;

namespace ExemploMVC.Controllers
{
    public class PaginasController : Controller
    {   
        public ActionResult Novo()
        {
            return View();
        }

        public ActionResult Index()
        {
            try
            {
                ViewBag.Paginas = new BusinessPagina().ListaPaginas();
            }
            catch (ApplicationException ex)
            {
                TempData["Erro"] = ex.Message;
                //Response.Redirect("/alerta");
            }

            return View();
        }

        public ActionResult Editar(Guid id)
        {
            ViewBag.Pagina = new BusinessPagina().BuscarPorId(id);
            return View();
        }
        
        [HttpPost]
        public void Criar()
        {
            try            
            {
                BusinessPagina businessPagina = new BusinessPagina();
                businessPagina.Nome = Request["nome"];
                businessPagina.Conteudo = Request["conteudo"];
                businessPagina.Data = DateTime.Now;
                businessPagina.Status = "Start";
                businessPagina.Diretorio = Request["diretorio"];
                businessPagina.Criar();
            }
            catch
            {
                TempData["Erro"] = "Falha ao criar os dados.";
            }

            Response.Redirect("/paginas");

        }

        [HttpPost]
        public void Alterar()
        {
            try
            {
                BusinessPagina businessPagina = new BusinessPagina();
                businessPagina.Id = Guid.Parse(Request["id"].ToString());
                businessPagina.Nome = Request["nome"];
                businessPagina.Conteudo = Request["conteudo"];
                businessPagina.Data = DateTime.Now;
                businessPagina.Status = Request["Status"].ToString();
                businessPagina.Alterar();
                TempData["Sucesso"] = "Dados alterados com sucesso";
            }
            catch
            {
                TempData["Erro"] = "Falha ao alterar os dados.";
            }

            Response.Redirect("/paginas");
        }

        public void Excluir(Guid id)
        {
            try
            {
                new BusinessPagina().Excluir(id);
                TempData["Sucesso"] = "Dados excluídos com sucesso";
            }
            catch
            {
                TempData["Erro"] = "Falha ao excluir os dados.";
            }

            Response.Redirect("/paginas");
        }
    }
}

Views/Home/Index.cshtml
<div class="jumbotron">
    <h3>Cadastro de Páginas</h3>
    <div>
        <a href="/paginas" class="btn btn-default">Cadastrar</a>
    </div>
</div>

Views/Paginas/Editar.cshtml
@{
    ViewBag.Title = "Novo";
    Business.BusinessPagina _dadosCliente = ViewBag.Pagina;
}

<h2>Editar Cliente</h2>
<div class="jumbotron">
    <div>
        <a href="/paginas" class="btn btn-default">Voltar</a>
    </div>
    <form action="/paginas/@_dadosCliente.Id/alterar" method="post">
        <div class="form-group">
            <label for="nome">Id:</label>
            <input type="text" class="form-control" id="id" name="id" value="@_dadosCliente.Id" readonly />
            <label for="nome">Nome:</label>
            <input type="text" class="form-control" id="nome" name="nome" value="@_dadosCliente.Nome" />
            <label for="diretorio">Observação</label>
            <textarea id="conteudo" name="conteudo" class="form-control">@_dadosCliente.Conteudo</textarea>
            <br />
            <select name="status" id="staus">
                <option value="Start">Start</option>
                <option value="Stop">Stop</option>
                <option value="Suspend">Suspend</option>
            </select>
        </div>
        <button type="submit" class="btn btn-default">Salvar</button>
    </form>
</div>

Views/Paginas/Index.cshtml
@{
    ViewBag.Title = "Páginas";
    List<Business.BusinessPagina> paginas = ViewBag.Paginas;
}

<script>
    var ValidarExclusao1 = function (id, evento) {
        if (confirm("Confirma a exclusão?")) {
            return true;
        }
        else {
            evento.preventDefault();
            return false;
        }
    }
</script>

@if(TempData["Sucesso"] != null)
{
    <div class="alert alert-success">@TempData["Sucesso"]</div>
}

@if(TempData["Erro"] != null)
{
    <div class="alert alert-danger">@TempData["Erro"]</div>
}

<div class="jumbotron">
    <h3>Processos Clientes</h3>
    <div>
        <a href="/paginas/novo" class="btn btn-default">Novo cliente</a>
    </div>
    <table class="table">
        <tr>
            <td>ID</td>
            <td>Nome</td>
            <td>Observação</td>
            <td>Data</td>
            <td>Status</td>
            <td></td>
            <td></td>
        </tr>

        @if (TempData["Erro"] == null)
        {
            foreach (var data in paginas)
            {
                <tr>
                    <td>@data.Id</td>
                    <td>@data.Nome</td>
                    <td>@data.Conteudo</td>
                    <td>@data.Data</td>
                    <td>@data.Status.ToString()</td>
                    <td>
                        <a href="/paginas/@data.Id/editar" class="btn btn-primary">Editar</a>
                    </td>
                    <td>
                        <a href="/paginas/@data.Id/excluir" class="btn btn-danger" onclick="ValidarExclusao(@data.Id, event)">Excluir</a>
                    </td>
                </tr>
            }
        }
    </table>
</div>

Views/Paginas/Novo.cshtml
@{
    ViewBag.Title = "Novo";
}

<h2>Novo Cliente</h2>
<div class="jumbotron">
    <div>
        <a href="/paginas" class="btn btn-default">Voltar</a>
    </div>
    <form action="/paginas/criar" method="post">
        <div class="form-group">
            <label for="nome">Cliente</label>
            <input type="text" class="form-control" id="nome" name="nome" />
            <label for="diretorio">Observação</label>
            <textarea id="conteudo" name="conteudo" class="form-control"></textarea>
            <label for="status">Status</label>
            <br />
            <select name="status" id="staus">
                <option value="Start">Start</option>
                <option value="Stop">Stop</option>
                <option value="Suspend">Suspend</option>
            </select>
        </div>
        <button type="submit" class="btn btn-default">Salvar</button>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Prova DTI</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/validacoes.js")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Processos", "Index", "Paginas", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Prova DTI</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>